### ISSUE TITLE
how can I set different ssh user for different roles?

### ISSUE THREAD

**Issue by allen12921** [fernandocarletti/capistrano-aws#10]
May I know how can we specify different ssh user for different role when working with capistrano-aws?

**Comment by fernandocarletti** [comment]
I believe you can achieve it by using the SSH Agent. You can add multiple keys and it will pick the correct one for that server.

**Comment by allen12921** [comment]
Hi @fernandocarletti 
  we know we can add multiple keys to ssh agent..the problem is we don't know how to specify different user name when work with capistrano-aws 
For example, we have server_A and server_B,we need use user_A connect to server_A and user_B to connect server_B.
In original capistrano  configuration we can set 'user' option in server definition in env.rb as below:
server 'server_role_1', user: 'user1', roles: [xxx], ssh_options: { host_name: 'myserver.com' }
But when work with capistrano-aws there is no place to do such configurations and only can set a global user as below:
aws_ec2_register user: 'hello', port: 2222

**Comment by fernandocarletti** [comment]
It was intentional to have it global, since it is tricky to define a user per server in a dynamic infra. Maybe you can use the `aws_ec2_extra_filters` configuration to filter the servers you need for that specific user.

**Comment by allen12921** [comment]
oh I see that thanks anyway.
