### ISSUE TITLE
Colorize dependecy grants GPLv2 license

### ISSUE THREAD

**Issue by cmmabee** [fernandocarletti/capistrano-aws#18]
While the license listed in this repository is MIT, the dependency on the `colorize` gem automatically grants the GPLv2 license. This puts `capistrano-aws` in grey territory legally for commercial use. If used commercially, software distributed with `capistrano-aws` would be forced to adhere to the terms of GPLv2.

Please consider using a gem like `rainbow` with a more open license instead.

**Comment by fernandocarletti** [comment]
Hello @cmmabee! Thanks for bringing this up, I really missed it. I'm not maintaining this gem since I stopped using Capistrano a few years ago, but I'll try to take some time to change the gem so the licensing doesn't affect whoever is still using it.

Best!

**Comment by cmmabee** [comment]
Hey @fernandocarletti! Thank you for the quick response. I don't want it to be a burden, so if you want me to put some time into it, I can fork a copy and help out. Let me know.

**Comment by fernandocarletti** [comment]
@andyspix just made the changes. I'll be publishing the gem after my work hours today.

**Comment by fernandocarletti** [comment]
It's released. Thanks @cmmabee and @andyspix!

https://rubygems.org/gems/capistrano-aws/versions/1.3.0
